# Generated by Django 2.2.5 on 2019-09-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='region',
            field=models.IntegerField(),
        ),
    ]
