# Generated by Django 2.2.5 on 2019-11-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20191120_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
