# Generated by Django 2.2.5 on 2019-11-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_voter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='finger',
            field=models.IntegerField(null=True),
        ),
    ]
